// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htcqyakbkyhoxvdxlfax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0Y3F5YWtia3lob3h2ZHhsZmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODcwODAsImV4cCI6MjA2MTY2MzA4MH0.umudRmhAm3B6JWpXFFIdeYVXO7M5eRfJmiUyqusZnxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);